name: Deploy documentation

on:
  push:
    branches:
    - docs-experiments

permissions:
  contents: write
  pull-requests: read

jobs:
  build_api_docs:
    name: Build Dokka (Jekyll)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 1.17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/gradle-build-action@v3.5.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build api documentation
        run: ./gradlew dokkaJekyll
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apidocs
          path: core/build/dokka/

  build_mkdoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install MkDocs and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material
        pip install mkdocs-minify-plugin
        pip install 'mkdocstrings[kotlin]'

    - name: Build the MkDocs site
      run: |
        mkdocs build

    - name: Upload 
      uses: actions/upload-artifact@v4
      with:
          name: mkdocstuff
          path: ./site

  deploy_mkdoc:
    needs: [build_mkdoc, build_api_docs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        id: download
        with:
          name: mkdocstuff
          path: public
          
      - name: Deploy MkDoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{steps.download.outputs.download-path}}
          destination_dir: docs

  deploy-api-docs:
    needs: deploy_mkdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        id: download
        with:
          name: apidocs
          path: public

      - name: Deploy API documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{steps.download.outputs.download-path}}
          destination_dir: docs/api
