name: Deploy documentation

on:
  push:
    branches:
    - docs-experiments

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install MkDocs and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material
        pip install mkdocs-minify-plugin
        pip install 'mkdocstrings[kotlin]'

    - name: Build the MkDocs site
      run: |
        mkdocs build --strict

    - name: Upload 
      uses: actions/upload-artifact@v4
      with:
          name: artifacts
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        id: download
        with:
          name: artifacts
          path: public
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{steps.download.outputs.download-path}}
          destination_dir: docs
