name: Publish to Maven Local

on:
  push:
    branches:
      - maven-setup

jobs:
  publish:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Configure GPG for loopback pinentry mode
        run: |
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpg-connect-agent reloadagent /bye

      - name: Build and publish to Maven (local)
        run: ./gradlew publish

      - name: Sign all published artifacts
        run: |
          ./gradlew signing
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
