name: Publish to Maven Local

on:
  push:
    branches:
      - maven-setup

jobs:
  publish:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set up GPG trust
        run: |
          KEY_ID=$(gpg --list-keys --keyid-format LONG | grep "^pub" | sed -E 's/^.* ([0-9A-F]{16}).*/\1/')
          echo "$KEY_ID:6:" | gpg --import-ownertrust

      - name: Build and publish to Maven (local)
        run: ./gradlew publish

      - name: Sign all published artifacts
        run: |
          ./gradlew signing
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
